project_name: cb

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: .
    binary: cb
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      386: i386
      amd64: x86_64
      darwin: darwin
      linux: linux
      windows: windows
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
